### ISSUE TITLE
Run class file command doesn't get executed

### ISSUE THREAD

**Issue by kaivalya97** [Johnothing/vscode-java-debug#1]
First of all, great to see that someone developed Compile and Run extension for Java in Visual Studio Code. 

The alt+c shortcut works perfectly and the .class file is also generated. However, the alt+r shortcut generates the command to be executed but somehow, it doesn't run in the console. Note that the bottom bar of VS Code displays the command to be executed.

I have attached the screenshots below that show that the command to run the Java code is not executed.

I hope this issue is solved by you at the earliest. Thanks once again for developing this extension.

![1](https://cloud.githubusercontent.com/assets/18525022/15585443/e67f885a-239c-11e6-87b6-783f05bb4d7e.JPG)
![2](https://cloud.githubusercontent.com/assets/18525022/15585444/e6a1a886-239c-11e6-814c-9acf7e830a69.JPG)

**Comment by D-Snake** [comment]
Well, thanks for your feedback. I am very busy，recently. So, I will handle this as far as possible. by the   way, I am not good at English either. :smile:

**Comment by Bintopia** [comment]
Well, thanks for your feedback. Same reason as issuse #4
