### ISSUE TITLE
Only Capable of Compiling Single File Projects

### ISSUE THREAD

**Issue by hofcake** [Johnothing/vscode-java-debug#4]
Possibly add the feature to compile all java files within the current working directory? Currently I am only able to compile single files. Perhaps we could add the path to the working directory in the config and just run that with *.java tacked on the end.

**Comment by isakhauge** [comment]
Hi! I am having the same problem. Right now I am using the terminal and entering "javac -encoding utf8 *.java"

Is there a possibility that you can include a way to compile all files within the same DIR?

**Comment by Bintopia** [comment]
Since there is a better extension [Language support for Java ™ for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=redhat.java) 👍 officially supported by RedHat. So,  I'm not going to go further any more. I suggest your guys using instead. Best wishes! 😃
