### ISSUE TITLE
Don't support packages 

### ISSUE THREAD

**Issue by josephponte** [Johnothing/vscode-java-debug#7]
I've created a java class "HolaMundo" in the pachage me.learn.basics, in the respective folder structure. I've got compile using ALT+C hotkey successfully, however, when I try to run using ALT+R hotkey shows a message that no class found.

![screen1](https://user-images.githubusercontent.com/22128533/33521396-2c5b1922-d7b8-11e7-8e83-ac72ff1babed.png)

![screen2](https://user-images.githubusercontent.com/22128533/33521401-3537c23e-d7b8-11e7-9dc2-e5d9c7f7e015.png)

![screen3](https://user-images.githubusercontent.com/22128533/33521402-3c72d1e2-d7b8-11e7-819f-45fb19b6feef.png)

**Comment by Bintopia** [comment]
Same reason as issuse #4
